# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

service:
  port: 80

image:
  secret: default-us-icr-io

ingress:
  subdomain: web
  domain: kui.us-south.containers.appdomain.cloud