# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

service:
  port: 80

ingress:
  subdomain: web
  domain: iqs-events.us-south.containers.appdomain.cloud