apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "{{ .Values.certSecret }}"
spec:
  secretName: "{{ .Values.certSecret }}"
  dnsNames:
  - www.kui.wtf
  - www.kui.tools
  - www.kuishell.org
  acme:
    config:
    - http01:
        ingressClass: "{{ .Values.ingressClass }}"
      domains:
      - www.kui.wtf
      - www.kui.tools
      - www.kuishell.org
  issuerRef:
    name: "{{ .Values.certIssuer }}"
    kind: ClusterIssuer